- name: Link config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ remark__linked_files }}"
