- import_tasks: ../common/tasks/apt.yml
  vars:
    packages: "{{ system__apt_packages }}"

- name: Create config paths
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ system__applications_config_path }}"

- import_tasks: ../common/tasks/link-config-files.yml
  vars:
    linked_files: "{{ system__linked_files }}"

- name: Import Gnome Terminal settings
  command: dconf load /org/gnome/terminal/ <<" EOF" {{ system__gnome_terminal_settings }} EOF
  changed_when: false
