node__apt_signing_keys:
  - https://deb.nodesource.com/gpgkey/nodesource.gpg.key

node__apt_repositories:
  - repo: deb https://deb.nodesource.com/node_8.x stretch main
    filename: nodesource
  - repo: deb-src https://deb.nodesource.com/node_8.x stretch main
    filename: nodesource

node__apt_packages:
  - node
  - yarn

node__npm_packages:
  - "@sonarwhal/configuration-progressive-web-apps"
  - "@sonarwhal/configuration-web-recommended"
  - axe-cli
  - bower
  - fast-cli
  - npm
  - pa11y
  - sonarwhal
  - svgo

node__linked_files:
  - .sonarwhalrc
