node__apt_signing_keys:
  - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  - https://dl.yarnpkg.com/debian/pubkey.gpg

node__apt_repositories:
  - repo: deb https://deb.nodesource.com/node_8.x stretch main
    filename: nodesource
  - repo: deb-src https://deb.nodesource.com/node_8.x stretch main
    filename: nodesource
  - repo: deb https://dl.yarnpkg.com/debian stable main
    filename: yarn

node__apt_packages:
  - nodejs
  - yarn

node__npm_packages:
  - "@sonarwhal/configuration-progressive-web-apps"
  - "@sonarwhal/configuration-web-recommended"
  - axe-cli
  - bower
  - fast-cli
  - pa11y
  - sonarwhal
  - svgo

node__linked_files:
  - .sonarwhalrc
