- name: Install packages with Homebrew-Cask
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ atom__homebrew_cask_packages }}"

- name: Create config path
  file:
    path: "{{ atom__config_path }}"
    state: directory

- name: Link config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ atom__linked_files }}"

- name: Install packages with apm
  command: "apm install {{ item }}"
  args:
    creates: "{{ atom__config_path }}/packages/{{ item }}"
  with_items: "{{ atom__apm_packages }}"
