- import_tasks: ../common/tasks/apt.yml
  vars:
    packages: "{{ atom__apt_packages }}"
    repositories: "{{ atom__apt_repositories }}"
    signing_keys: "{{ atom__apt_signing_keys }}"

- name: Create config path
  file:
    path: "{{ atom__config_path }}"
    state: directory

- import_tasks: ../common/tasks/link-config-files.yml
  vars:
    linked_files: "{{ atom__linked_files }}"

- name: Install packages with apm
  command: "apm install {{ item }}"
  args:
    creates: "{{ atom__config_path }}/packages/{{ item }}"
  with_items: "{{ atom__apm_packages }}"
