- name: Install tmux with Homebrew
  homebrew:
    name: tmux
    state: latest

- name: Link configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
  with_items: "{{ tmux_linked_files }}"
