- name: Install packages with Homebrew
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ tmux__homebrew_packages }}"

- name: Link config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ tmux__linked_files }}"
