- name: Add APT signing keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ node__apt_signing_keys }}"

- name: Add APT repositories
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename }}"
    state: present
  with_items: "{{ node__apt_repositories }}"

- import_tasks: ../common/tasks/apt.yml
  vars:
    packages: "{{ node__apt_packages }}"

- name: Install packages with npm
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ node__npm_packages }}"

- import_tasks: ../common/tasks/link-config-files.yml
  vars:
    linked_files: "{{ node__linked_files }}"
