- import_tasks: ../common/tasks/apt.yml
  vars:
    packages: "{{ node__apt_packages }}"
    repositories: "{{ node__apt_repositories }}"
    signing_keys: "{{ node__apt_signing_keys }}"

- name: Install packages with npm
  npm:
    name: "{{ item }}"
    global: yes
    path: "{{ lookup('env', 'HOME') }}/.node_modules"
  with_items: "{{ node__npm_packages }}"
