- import_tasks: ../common/tasks/apt.yml
  vars:
    packages: "{{ ruby__apt_packages }}"

- name: Create config paths
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ruby__bundler_config_path }}"
    - "{{ ruby__rbenv_config.path }}"

- name: Install rbenv
  git:
    repo: "{{ ruby__rbenv_config.repo }}"
    dest: "{{ ruby__rbenv_config.path }}"

- name: Create rbenv plugins folder
  file:
    path: "{{ ruby__rbenv_config.path }}/plugins"
    state: directory
  register: ruby__rbenv_plugins_config

- name: Install rbenv plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ruby__rbenv_plugins_config.path }}/{{ item.name }}"
  with_items: "{{ ruby__rbenv_config.plugins }}"

- import_tasks: ../common/tasks/link-config-files.yml
  vars:
    linked_files: "{{ ruby__linked_files }}"

- name: Create {{ ruby__default_gems_config }} file
  template:
    src: default-gems.j2
    dest: "{{ ruby__default_gems_config }}"

- name: Install Ruby versions
  shell: "{{ ansible_env.SHELL }} -lc '{{ ruby__rbenv_config.path }}/bin/rbenv install --skip-existing {{ item }}'"
  register: ruby__install_ruby_result
  changed_when: ruby__install_ruby_result.stdout != ''
  with_items: "{{ ruby__versions }}"

- name: Set global Ruby version
  command: rbenv global {{ ruby__global_version }}
  changed_when: false
