- name: Install packages with Homebrew
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ruby__homebrew_packages }}"

- name: Create config paths
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ruby__bundler_config_path }}"
    - "{{ ruby__rbenv_config_path }}"

- name: Link config files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ ruby__linked_files }}"

- name: Create {{ ruby__default_gems_config }} file
  template:
    src: default-gems.j2
    dest: "{{ ruby__default_gems_config }}"

- name: Install Ruby versions
  command: "rbenv install {{ item }}"
  args:
    creates: "{{ ruby__rbenv_config_path }}/versions/{{ item }}"
  with_items: "{{ ruby__versions }}"

- name: Set global Ruby version
  command: "rbenv global {{ ruby__global_version }}"
  changed_when: false
